packages:
  - "packages/*"
  - "site"

linkWorkspacePackages: true
preferWorkspacePackages: true
autoInstallPeers: false

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - "@tarojs/binding"
  - "@tarojs/cli"
  - esbuild
  - lefthook
  - nx
  - unrs-resolver

overrides:
  "@types/minimatch": "6.0.0"
  enhanced-resolve: "5.22.2"
